from jobs.dctree.trainsalary import tree
import time
start = time.clock()
if __name__ == '__main__':
    #    print "please use: python decision.py train_file test_file"
    #    sys.exit()
    train_file = 'd:/jobs/dctree/salary/train.csv'
    test_file = 'd:/jobs/dctree/salary/test.csv'
    #run(train_file,test_file)
#     tree.run(train_file, test_file, 0.080)
#     tree.test(train_file, test_file, 'result080.txt')
#     tree.run(train_file, test_file, 0.081)
#     tree.test(train_file, test_file, 'result081.txt')
#     tree.run(train_file, test_file, 0.082)
#     tree.test(train_file, test_file, 'result082.txt')
#     tree.run(train_file, test_file, 0.083)
#     tree.test(train_file, test_file, 'result083.txt')
#     tree.run(train_file, test_file, 0.084)
#     tree.test(train_file, test_file, 'result084.txt')
#     tree.run(train_file, test_file, 0.085)
#     tree.test(train_file, test_file, 'result085.txt')
#     tree.run(train_file, test_file, 0.086)
#     tree.test(train_file, test_file, 'result086.txt')
#     tree.run(train_file, test_file, 0.087)
#     tree.test(train_file, test_file, 'result087.txt')
#     tree.run(train_file, test_file, 0.088)
#     tree.test(train_file, test_file, 'result088.txt')
#     tree.run(train_file, test_file, 0.089)
#     tree.test(train_file, test_file, 'result089.txt')
#     tree.run(train_file, test_file, 0.090)
#     tree.test(train_file, test_file, 'result090.txt')
#     tree.run(train_file, test_file, 0.091)
#     tree.test(train_file, test_file, 'result091.txt')
#     tree.run(train_file, test_file, 0.092)
#     tree.test(train_file, test_file, 'result092.txt')
#     tree.run(train_file, test_file, 0.093)
#     tree.test(train_file, test_file, 'result093.txt')
#     tree.run(train_file, test_file, 0.094)
#     tree.test(train_file, test_file, 'result094.txt')
#     tree.run(train_file, test_file, 0.095)
#     tree.test(train_file, test_file, 'result095.txt')
#     tree.run(train_file, test_file, 0.096)
#     tree.test(train_file, test_file, 'result096.txt')
#     tree.run(train_file, test_file, 0.097)
#     tree.test(train_file, test_file, 'result097.txt')
#     tree.run(train_file, test_file, 0.098)
#     tree.test(train_file, test_file, 'result098.txt')
#     tree.run(train_file, test_file, 0.099)
#     tree.test(train_file, test_file, 'result099.txt')
    tree.run(train_file, test_file, 0.10)
    tree.test(train_file, test_file, 'result10.txt')
    tree.run(train_file, test_file, 0.11)
    tree.test(train_file, test_file, 'result11.txt')
    tree.run(train_file, test_file, 0.12)
    tree.test(train_file, test_file, 'result12.txt')
    tree.run(train_file, test_file, 0.13)
    tree.test(train_file, test_file, 'result13.txt')
    tree.run(train_file, test_file, 0.14)
    tree.test(train_file, test_file, 'result14.txt')
    tree.run(train_file, test_file, 0.15)
    tree.test(train_file, test_file, 'result15.txt')
    tree.run(train_file, test_file, 0.16)
    tree.test(train_file, test_file, 'result16.txt')
    tree.run(train_file, test_file, 0.17)
    tree.test(train_file, test_file, 'result17.txt')
    tree.run(train_file, test_file, 0.18)
    tree.test(train_file, test_file, 'result18.txt')
    tree.run(train_file, test_file, 0.19)
    tree.test(train_file, test_file, 'result19.txt')
    tree.run(train_file, test_file, 0.20)
    tree.test(train_file, test_file, 'result20.txt')
    tree.run(train_file, test_file, 0.21)
    tree.test(train_file, test_file, 'result21.txt')
    tree.run(train_file, test_file, 0.22)
    tree.test(train_file, test_file, 'result22.txt')
    tree.run(train_file, test_file, 0.23)
    tree.test(train_file, test_file, 'result23.txt')
    tree.run(train_file, test_file, 0.24)
    tree.test(train_file, test_file, 'result24.txt')
    tree.run(train_file, test_file, 0.25)
    tree.test(train_file, test_file, 'result25.txt')
    tree.run(train_file, test_file, 0.26)
    tree.test(train_file, test_file, 'result26.txt')
    tree.run(train_file, test_file, 0.27)
    tree.test(train_file, test_file, 'result27.txt')
    tree.run(train_file, test_file, 0.28)
    tree.test(train_file, test_file, 'result28.txt')
    tree.run(train_file, test_file, 0.29)
    tree.test(train_file, test_file, 'result29.txt')
    
end = time.clock()
print (end - start)