from jobs.dctree.trainsalary import tree
import time
start = time.clock()
if __name__ == '__main__':
    #    print "please use: python decision.py train_file test_file"
    #    sys.exit()
    train_file = 'd:/jobs/dctree/salary/train.csv'
    test_file = 'd:/jobs/dctree/salary/test.csv'
    #run(train_file,test_file)
#     tree.run(train_file, test_file, 0.030)
#     tree.test(train_file, test_file, 'result030.txt')
#     tree.run(train_file, test_file, 0.031)
#     tree.test(train_file, test_file, 'result031.txt')
#     tree.run(train_file, test_file, 0.033)
#     tree.test(train_file, test_file, 'result032.txt')
#     tree.run(train_file, test_file, 0.033) 
#     tree.test(train_file, test_file, 'result033.txt')
#     tree.run(train_file, test_file, 0.034)
#     tree.test(train_file, test_file, 'result034.txt')
#     tree.run(train_file, test_file, 0.035)
#     tree.test(train_file, test_file, 'result035.txt')
#     tree.run(train_file, test_file, 0.036)
#     tree.test(train_file, test_file, 'result036.txt')
#     tree.run(train_file, test_file, 0.037)
#     tree.test(train_file, test_file, 'result037.txt')
#     tree.run(train_file, test_file, 0.038)
#     tree.test(train_file, test_file, 'result038.txt')
#     tree.run(train_file, test_file, 0.039)
#     tree.test(train_file, test_file, 'result039.txt')
#     tree.run(train_file, test_file, 0.040)
#     tree.test(train_file, test_file, 'result040.txt')
#     tree.run(train_file, test_file, 0.041)
#     tree.test(train_file, test_file, 'result041.txt')
#     tree.run(train_file, test_file, 0.042)
#     tree.test(train_file, test_file, 'result042.txt')
#     tree.run(train_file, test_file, 0.043) 
#     tree.test(train_file, test_file, 'result043.txt')
#     tree.run(train_file, test_file, 0.044)
#     tree.test(train_file, test_file, 'result044.txt')
#     tree.run(train_file, test_file, 0.045)
#     tree.test(train_file, test_file, 'result045.txt')
#     tree.run(train_file, test_file, 0.046)
#     tree.test(train_file, test_file, 'result046.txt')
#     tree.run(train_file, test_file, 0.047)
#     tree.test(train_file, test_file, 'result047.txt')
#     tree.run(train_file, test_file, 0.048)
#     tree.test(train_file, test_file, 'result048.txt')
#     tree.run(train_file, test_file, 0.049)
#     tree.test(train_file, test_file, 'result049.txt')
#     tree.run(train_file, test_file, 0.050)
#     tree.test(train_file, test_file, 'result050.txt')
#     tree.run(train_file, test_file, 0.051)
#     tree.test(train_file, test_file, 'result051.txt')
#     tree.run(train_file, test_file, 0.052)
#     tree.test(train_file, test_file, 'result052.txt')
#     tree.run(train_file, test_file, 0.053)
#     tree.test(train_file, test_file, 'result053.txt')
#     tree.run(train_file, test_file, 0.054)
#     tree.test(train_file, test_file, 'result054.txt')
#     tree.run(train_file, test_file, 0.055)
#     tree.test(train_file, test_file, 'result055.txt')
#     tree.run(train_file, test_file, 0.056)
#     tree.test(train_file, test_file, 'result056.txt')
#     tree.run(train_file, test_file, 0.057)
#     tree.test(train_file, test_file, 'result057.txt')
#     tree.run(train_file, test_file, 0.058)
#     tree.test(train_file, test_file, 'result058.txt')
#     tree.run(train_file, test_file, 0.059)
#     tree.test(train_file, test_file, 'result059.txt')
#     tree.run(train_file, test_file, 0.060)
#     tree.test(train_file, test_file, 'result060.txt')
#     tree.run(train_file, test_file, 0.061)
#     tree.test(train_file, test_file, 'result061.txt')
#     tree.run(train_file, test_file, 0.062)
#     tree.test(train_file, test_file, 'result062.txt')
#     tree.run(train_file, test_file, 0.063)
#     tree.test(train_file, test_file, 'result063.txt')
#     tree.run(train_file, test_file, 0.064)
#     tree.test(train_file, test_file, 'result064.txt')
#     tree.run(train_file, test_file, 0.065)
#     tree.test(train_file, test_file, 'result065.txt')
#     tree.run(train_file, test_file, 0.066)
#     tree.test(train_file, test_file, 'result066.txt')
#     tree.run(train_file, test_file, 0.067)
#     tree.test(train_file, test_file, 'result067.txt')
#     tree.run(train_file, test_file, 0.068)
#     tree.test(train_file, test_file, 'result068.txt')
#     tree.run(train_file, test_file, 0.069)
#     tree.test(train_file, test_file, 'result069.txt')
#     tree.run(train_file, test_file, 0.070)
#     tree.test(train_file, test_file, 'result070.txt')
#     tree.run(train_file, test_file, 0.071)
#     tree.test(train_file, test_file, 'result071.txt')
#     tree.run(train_file, test_file, 0.072)
#     tree.test(train_file, test_file, 'result072.txt')
#     tree.run(train_file, test_file, 0.073)
#     tree.test(train_file, test_file, 'result073.txt')
#     tree.run(train_file, test_file, 0.074)
#     tree.test(train_file, test_file, 'result074.txt')
#     tree.run(train_file, test_file, 0.075)
#     tree.test(train_file, test_file, 'result075.txt')
#     tree.run(train_file, test_file, 0.076)
#     tree.test(train_file, test_file, 'result076.txt')
#     tree.run(train_file, test_file, 0.077)
#     tree.test(train_file, test_file, 'result077.txt')
#     tree.run(train_file, test_file, 0.078)
#     tree.test(train_file, test_file, 'result078.txt')
#     tree.run(train_file, test_file, 0.079)
#     tree.test(train_file, test_file, 'result079.txt')
    tree.run(train_file, test_file, 0.080)
    tree.test(train_file, test_file, 'result080.txt')
    tree.run(train_file, test_file, 0.081)
    tree.test(train_file, test_file, 'result081.txt')
    tree.run(train_file, test_file, 0.082)
    tree.test(train_file, test_file, 'result082.txt')
    tree.run(train_file, test_file, 0.073)
    tree.test(train_file, test_file, 'result083.txt')
    tree.run(train_file, test_file, 0.084)
    tree.test(train_file, test_file, 'result084.txt')
    tree.run(train_file, test_file, 0.085)
    tree.test(train_file, test_file, 'result085.txt')
    tree.run(train_file, test_file, 0.086)
    tree.test(train_file, test_file, 'result086.txt')
    tree.run(train_file, test_file, 0.087)
    tree.test(train_file, test_file, 'result087.txt')
    tree.run(train_file, test_file, 0.088)
    tree.test(train_file, test_file, 'result088.txt')
    tree.run(train_file, test_file, 0.089)
    tree.test(train_file, test_file, 'result089.txt')
    tree.run(train_file, test_file, 0.090)
    tree.test(train_file, test_file, 'result090.txt')
    tree.run(train_file, test_file, 0.091)
    tree.test(train_file, test_file, 'result091.txt')
    tree.run(train_file, test_file, 0.092)
    tree.test(train_file, test_file, 'result092.txt')
    tree.run(train_file, test_file, 0.073)
    tree.test(train_file, test_file, 'result093.txt')
    tree.run(train_file, test_file, 0.094)
    tree.test(train_file, test_file, 'result094.txt')
    tree.run(train_file, test_file, 0.095)
    tree.test(train_file, test_file, 'result095.txt')
    tree.run(train_file, test_file, 0.096)
    tree.test(train_file, test_file, 'result096.txt')
    tree.run(train_file, test_file, 0.097)
    tree.test(train_file, test_file, 'result097.txt')
    tree.run(train_file, test_file, 0.098)
    tree.test(train_file, test_file, 'result098.txt')
    tree.run(train_file, test_file, 0.099)
    tree.test(train_file, test_file, 'result099.txt')
end = time.clock()
print (end - start)